version: "3.9"
services:
  api:
    build: 
      dockerfile: dockerfile
      context: .
    image: rest-api-security:1.0
    container_name: rest-security
    restart: unless-stopped
    working_dir: /home/node/app/api
    ports:
      - "3000:3000"
    stdin_open: true
    tty: true
    volumes:
      - ./api/:/home/node/app/api
      - ./test/:/home/node/app/test
      - ./package.json:/home/node/app/package.json
      - ./.eslintrc.json:/home/node/app/.eslintrc.json
      - dbFilePath.db.sqlite:/home/node/app/dbFilePath.db.sqlite
    env_file:
      - .env
    depends_on:
      - "redis"
  redis:
    image: redis:7.0.0-alpine
    volumes: 
      - cache:/data
volumes:
  dbFilePath.db.sqlite:
  cache: