version: "3.9"
services:
  api:
    build: 
      dockerfile: dockerfile
      context: .
    image: rest-api-security:1.0
    container_name: rest-security
    restart: unless-stopped
    working_dir: /home/node/app/api
    networks:
      - rest-api
    ports:
      - "3000:3000"
    stdin_open: true
    tty: true
    volumes:
      - ./api/:/home/node/app/api
      - ./package.json:/home/node/app/package.json
      - ./.eslintrc.json:/home/node/app/.eslintrc.json
      - ./.env:/home/node/app/.env
      - ./dbFilePath.db:/home/node/app/dbFilePath.db
networks:
  rest-api:
    driver: bridge